### ISSUE TITLE
Option to add lambda_function_association to the dynamic ordered cache behaviour

### ISSUE THREAD

**Issue by qamar-ali** [jmgreg31/terraform-aws-cloudfront#3]
Option to add lambda_function_association to the dynamic ordered cache behaviour
eg:
 dynamic "ordered_cache_behavior" {
for_each = [for i in "${var.dynamic_ordered_cache_behavior}" : {
lambda_function_association = i.lambda_function_association
}]
content{
lambda_function_association = [ordered_cache_behavior.value.lambda_function_association]
}
}

**Comment by jmgreg31** [comment]
@qamar-ali Thanks for the feedback.  I submitted a PR for this fix and will merge if there are no objections

**Comment by qamar-ali** [comment]
Thanks for adding it up @jmgreg31 , however we cant have a optional variable for this.
As null or "" assignment is not accepted, coz the origins which does not required lambda association fails if the value is null to var.dynamic_lambda_function_association_ordered

the dynamic association of config blocks needs to optional in case some origins doesn't required that.

**Comment by qamar-ali** [comment]
Also if we have two separate variable blocks for ordered origins, like.
```
dynamic_ordered_cache_behavior = [
  {
    path_pattern           = "/cafe/"
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "mydomain2origin.google.com"
    compress               = false
    query_string           = true
    cookies_forward        = "all"
    headers                = []
    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 0
    max_ttl                = 0
  }
]
```

```
  dynamic_lambda_function_association_ordered = [
   {
    lambda_arn                = "arn:aws:lambda:xxxx"
    event_type                = "origin-request"
    include_body              = false
   },
 ]
```

The precedence to associate each will differ as the first block will execute with 0 precedence until the last in the map ,and the lambda function block will iterate over too.

We cant say that ,if precedence 0  doesn't require the lambda edge association to be skipped in this case.

**Comment by jmgreg31** [comment]
@qamar-ali I wasn’t able to reproduce the issue of failing the cache behavior if the association was empty.  Is this for default or ordered or both?  I am able to run the example module without having the associations configured.

The second issue you mention is one I hadn’t thought of and am honestly not to sure how to solve at the moment.  I will think this one over

**Comment by qamar-ali** [comment]
@jmgreg31 yes regarding the first one ,yes we can keep it optionalthat means the module will not have lambda association at all, only thing i was checking was on the second one where in we can optionally have ordered behaviours to associate lambda edge based on their precedence and skip if not required.

**Comment by jmgreg31** [comment]
@qamar-ali I was able to understand the issue more clearly, and at this time I don't have a solution. I have posed some questions https://github.com/terraform-providers/terraform-provider-aws/issues/8873 to hopefully clarify how to do this

**Comment by jmgreg31** [comment]
@qamar-ali Sorry for the long wait on this.  My attention was brought back to this issue in reference to some other changes that needed to be made.  Once #10 is merged, you will be able to add `lambda_function_association` to any cache behavior as well as create as many as you want.  Please reference the example terraform.tfvars for variable specifics
